<CubeWidget>:
    button:button
    Button:
        id:button
        canvas.before:
            Color:
                rgba:(0,0,0,1)
            Line:
                width:2
                rectangle:0,0,self.width,self.height
        background_normal:''
        background_color:root.initcolor
<New_Board>:
    rows:8
    cols:8
    size_hint:1,None
    height:self.width
    
    
    
         
        
                
